# Generated by Django 3.2 on 2022-02-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
